### ISSUE TITLE
Sliding windows limitation - window size must be multiple of slide by

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1431]
Sliding windows in Hazelcast Jet have following limitation: "The length of the window is an integer multiple of the step size".

However from usage point of view it makes sense to provide functionality also for windowing like "show me results for last 10seconds and do it every 3 seconds".

**Comment by mtopolnik** [comment]
This has performance and storage consequences. In the 10 seconds, slide by 3 seconds, we'd actually have to slide by 1 second internally and have 10 separate "buckets" for each window. If you specified 10 seconds, slide by 3.01 seconds, we'd need 1,000 buckets. Because this is a non-obvious consequence we decided not to support it.

**Comment by viliam-durina** [comment]
If you have one 1000ms window and one 999ms window in the pipeline, the conse

**Comment by cangencer** [comment]
We will not implement this for now, due to the performance considerations @mtopolnik noted above. It would require a complete rewrite of sliding window logic and would have worse performance.
