### ISSUE TITLE
Last stream window frame does not execute as expected

### ISSUE THREAD

**Issue by aliman17** [hazelcast/hazelcast-jet#1605]
I have noticed that the last window frame does not get executed until I create event that falls into new window frame and previous one finishes and returns result. 

To patch this, I tried to set early result period but this is executing all the time even if I don't have new events. 

I don't understand this behaviour. 

What I would expect is that windows frame get executed once it exceeded certain time. For example, if I set 5sec time frame it would execute at 12:00:00, 12:00:05, 12:00:10, etc. but it seems that the last one is always somehow stuck. 

What should I do to get the expected behaviour?

**Comment by cangencer** [comment]
Currently only advancing event time will close windows, so yes you need further events to close the current window.

**Comment by viliam-durina** [comment]
Jet uses event time. If events stop, it's as if time stopped. If you don't have a constant stream of evens, you could add heartbeat events which Jet will use to advance the time, but ignore otherwise. However if you have a partitioned source (such as Kafka or IMap Journal), each partition must have own heartbeats.

**Comment by aliman17** [comment]
Thank you. That answers my questions.

**Comment by aliman17** [comment]
How to make sure that each partition has it's own heartbeat? I'm using IMap.

**Comment by viliam-durina** [comment]
@aliman17 You have to do it on your own. You need a process that will know the partition list and will produce the messages just as it produces any other messages. You also need to make all consumers aware so that they filter out the heartbeat messages and don't crash when encountering an unknown message.

**Comment by aliman17** [comment]
Thanks.
