### ISSUE TITLE
Job queuesCapacity metrics not correctly set

### ISSUE THREAD

**Issue by TomaszGaweda** [hazelcast/hazelcast-jet#1638]
Hi,

While investigating #1617, I found that some metrics are being not correctly populated.

For one mapUsingContext node for example I see:
queuesSize: 0
receivedCount: 12
receivedBatches: 2
queuesCapacity: 0

First 3 seems to be correct, but queuesCapacity is for sure incorrect. Even if it's by design, the values are confusing for end users and should be correct or not appear at all

**Comment by viliam-durina** [comment]
`queuesCapacity` is 0 for sources (because they have no input). You'll also see it for the final metrics after the job completes (I assume you're using Jet 3.2 now), there it's 0 for all vertices. It's for implementation reasons: we remove the input queues as they complete until the last sink has no input and itself ends, then the job completes. `queuesCapacity` can also change while the job is running if a vertex has inputs with multiple different priorities. First it shows capacity for highest priority ordinals, then the next and so on. You can interpret it as "the capacity of queues the processor is currently draining".

To add more confusion, you can see `queuesCapacity` larger than 0 in case a snapshot is restored because we internally restore the snapshot by adding a vertex, so the source is actually ingesting the snapshot data.

And even more confusion: you can theoretically see `queuesSize=1, queuesCapacity=0`. That is there's 1 item in a zero queues. This can happen because we read the metrics one by one and don't stop the execution during the process.
