### ISSUE TITLE
hello-world example does not print anything if submitted through CLI

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#1837]
In case when `hello-world` example jar from https://github.com/hazelcast/hazelcast-jet/tree/master/examples/hello-world is submitted through jet CLI then expected result is not printed. It seems it is caused by missing log4j properties.

We should provide and documented simple way how to run execute this code sample properly in https://github.com/hazelcast/hazelcast-jet/blob/d03eb34092aa7c66c47647967c24d42e72c66901/examples/hello-world/src/main/java/com/hazelcast/jet/examples/helloworld/HelloWorld.java#L38.

Current output is following:
```
log4j:WARN No appenders could be found for logger (com.hazelcast.jet.examples.helloworld.HelloWorld).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

It seems to be related to removing log4j from `jet` CLI in https://github.com/hazelcast/hazelcast-jet/commit/9051ec1ffb55d6504325d6945364397591fe3c0e

**Comment by cangencer** [comment]
This seems because log4j's classloader is different than the one used for the main class in HelloWorld, and it's not able to find the resource files. I tried setting TCCL but in JDK11 log4j because of buggy parsings thinks it's running in Java *1.1* and doesn't try to use TCCL (which was added in JDK 1.2)
