### ISSUE TITLE
Add mixins to all commands to configure address and cluster name

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#2045]
Currently the syntax is like `jet -a <address> -n <name> submit <jar> ..` which looks rather odd. We should allow adding address/name after the commands as well.

There might be a few conflicts because `-n` in submit command is already used for other parameters.

**Comment by caioguedes** [comment]
Hey @Holmistr, I would like to work on this. 😄

**Comment by Holmistr** [comment]
Hey @caioguedes , glad to see you back! :) I assigned you the issue.

I guess the issue is pretty self-explanatory, so I'm not going to take away the fun from you with more hints. However, if you feel like you need some or you're not clear on the requirements, feel free to ask here or on the Gitter channel. You're already a skilled contributor, so I don't have to explain the process to you :smile:
