### ISSUE TITLE
ReceiverTasklet might never receive END_ITEM and cause the job to hang

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast-jet#2158]
This is a code review issue with no known reproducers.

Paraphrasing @devozerov:

Hazelcast has the `Connection.write(Packet)` method that returns `true` if the `Packet` was scheduled for sending. It is possible that the packet will never be delivered to the target member even if the target member is alive (examples: a half-opened socket, intermittent network failure that breaks the underlying channel). Hazelcast components are able to recover from it thanks to retry logic in the invocation service. But Jet doesn't use it and writes packets directly (we do the same in SQL).

Now, consider the following sequence of events:

1. `SenderTasklet` reaches EOS in `tryFillInbox()`, writes `DONE_ITEM`
2. We try to send the last packet in the call method, `Connection.write()` returns `true`
3. The connection is broken and the packet is never sent
4. Jet doesn't use this connection anymore as EOS has been reached, so the failure goes unnoticed
5. Remote member never receives the packet

**Comment by devozerov** [comment]
I would propose to delete the part of the description with the proposed solution. It was an idea for IMDG SQL that has a different protocol. Moreover, now I tend to think that this solution doesn't work in SQL IMDG because there are a number of cases when the receiver might wait for a sender that doesn't exist. So most likely a different protocol will be implemented for SQL IMDG, and we are yet to find the solution.

I opened https://github.com/hazelcast/hazelcast/issues/16868 for SQL protocol fixes.

**Comment by viliam-durina** [comment]
A possible fix is this: When creating the flow control packet check that the Connection object is still the same. The RT can know the Connection and if the connection is different (the member reconnected), we can throw an error in the RT. We'll rely on that the connection is eventually re-established. A flow control packet contains information from all active receiver tasklets.
