### ISSUE TITLE
Create sources for benchmarking

### ISSUE THREAD

**Issue by cangencer** [hazelcast/hazelcast-jet#2244]
`TestSources.items()` and `TestSources.itemStream()`work well for unit testing but they're not optimised to give the best performance when we want to do some benchmarking:

* They use blocking threads
* The source itself is not distributed or partitioned
* `TestSources.itemStream` calls `System.currentTimeMillis()` for each item

**Comment by guenter-hesse** [comment]
Hi there,

I am interested in looking into this issue. However, having a brief look into the sources led to some questions:

- Where exactly did you discover the usage of blocking threads?
- WRT a distributed source: does that mean you would like to have something like `itemsDistributed()` and `itemStreamDistributed()` that return distributed version of `BatchSource` and `StreamSource`, respectively?

**Comment by cangencer** [comment]
Hi @guenter-hesse 

In Jet, we have [cooperative and non-cooperative sources](https://jet-start.sh/docs/architecture/execution-engine). The sources that use the SourceBuilder API are non-cooperative so they use blocking threads. This is maybe not a big issue as the source doesn't do much work.

With 4.2 we have introduced the rebalance operator which can turn a non-distributed source to distributed. I think the bigger issue is for example TestSources.items() needs to materialize all the items up front. Something like TestSources.range(0, 1000) with lazy materialization would work better. 

For some examples of high performance benchmarking sources I recommend you look at https://github.com/mtopolnik/jet-gc-benchmark/tree/master/src/main/java/org/example and the related articles at https://jet-start.sh/blog/

**Comment by mtopolnik** [comment]
This is I think the best way to create a distributed, high-throughput source: https://github.com/mtopolnik/jet-gc-benchmark/blob/master/src/main/java/org/example/ClusterBatchBenchmark.java#L28

```java
        p.readFrom(longSource())
         .rebalance()
         .flatMap(n -> {
             Long[] items = new Long[SOURCE_STEP];
             Arrays.setAll(items, i -> n + i);
             return traverseArray(items);
         })
```

Basically, the source generates batches of data without materializing the full batch. Then, after distributing them across the cluster, `flatMap` expands the batches.

**Comment by guenter-hesse** [comment]
The `TestSources` class, as the name suggests, creates source objects, however, `rebalance()` is provided by the `BatchStage` class. You can retrieve the latter from a source object via the `readFrom()` method as shown above, but I am not sure if that should be done inside the `TestSources` class. 

So if I understand you correctly @mtopolnik, you suggest applying logic at later stages (`rebalance`, `flatMap`) to source objects in order to do high-throughput testing. That means you would *not* change the `TestSources.items()` and `TestSources.itemStream()` methods linked in this issue, but rather adapt the code calling these methods - where distributed, high-throughput scenarios are supposed to be tested. 
Is that correct?

If so, I would suggest creating separate issues for these cases where code adaptions would benefit the testing purpose. I currently do not know where such high-throughput sources are needed.

Concerning this issue, at least the mentioned `tsNanos = TimeUnit.MILLISECONDS.toNanos(System.currentTimeMillis())` can be removed. Instead the already available `nowNs` can be used as far as I can see. I could create a corresponding PR.

Do you think that makes sense?

**Comment by mtopolnik** [comment]
You still need laziness in the source, that's the essential problem that Can implied. Also, because we have this useful idiom to create a high-throughput pipeline stage, I think we could capture it in an API call.

**Comment by mtopolnik** [comment]
>

**Comment by mtopolnik** [comment]
> Concerning this issue, at least the mentioned `tsNanos = TimeUnit.MILLISECONDS.toNanos(System.currentTimeMillis())` can be removed. Instead the already available nowNs can be used as far as I can see. I could create a corresponding PR.

In order to measure latencies, you must call the same current time method in a later stage. However, `System.nanoTime()` is only consistent on a single node, it's unusable for measuring cluster-wide latencies. 

As a workaround, I used this in the benchmarks and it served me well:

```java
private static long determineTimeOffset() {
    long milliTime = System.currentTimeMillis();
    long nanoTime = System.nanoTime();
    return NANOSECONDS.toMillis(nanoTime) - milliTime;
}
```

Then I can emit a timestamp like this:

```java
NANOSECONDS.toMillis(System.nanoTime()) - nanoTimeMillisToCurrentTimeMillis
```

**Comment by guenter-hesse** [comment]
Does that mean you just want to have methods added that provide a corresponding stage and keep the current methods `items()` and `itemStream()` as is, such as in the following commit?
https://github.com/guenter-hesse/hazelcast-jet/commit/e29ddb343d2fb1a0c229bd499dac2effb0188f8f

**Comment by cangencer** [comment]
@guenter-hesse a good start would be to create something like `TestSources.range(0, 1_000_000_000L)` for example: this would emit 1B items, in a lazy way. This is not achievable by TestSources.items(). Does it make sense?

**Comment by guenter-hesse** [comment]
That is basically what, e.g., `batchStageForLongRange(Pipeline pipeline, long range, int stepSize)` is doing in the referenced commit, except for the possibility to specify a lower range bound. As suggested, it is very much oriented on the mentioned https://github.com/mtopolnik/jet-gc-benchmark/blob/master/src/main/java/org/example/ClusterBatchBenchmark.java#L28 

Am I overseeing something or does the commit include what you mean?
If a lower range bound is needed, I can of course try to include that.

**Comment by cangencer** [comment]
OK yes, that's in the right direction. However the source should typically only return the Source itself and not a stage, this is the convention followed by all the other sources. @mtopolnik 's approach seems a bit different in that it creates the stage directly. It might be easier if you send a PR and we can comment on the code directly?
