### ISSUE TITLE
Cdc sink can contain incorrect value if sequence source is changed and reordering happened

### ISSUE THREAD

**Issue by olukas** [hazelcast/hazelcast-jet#2367]
In case when sequence source was changed (e.g. cdc source reconnect to different db) and reordering between old and new sequence source happened then cdc sink will contain latest value which it obtained (independently on their real order).

Example (`update<x,y,z>` means update message from source `x`, with sequence number `y` and content `z`. In this example all messages are updates for the same `id`):
Real order of messages:
`update<0,0,u0>`
`update<0,1,u1>`
`update<1,0,u2>`
`update<1,1,u3>`

They can be reordered and see by sink like:
`update<0,0,u0>`
`update<1,1,u3>`
`update<0,1,u1>`
`update<1,0,u2>`

In this case Cdc sink will contain value `u2` instead of correct value `u3`.

Once when global Jet reordering will be fixed/implemented then it fix this issue as well.

**Comment by jbartok** [comment]
Since the CDC source is non-distributed, I think the **Preserve Event Reordering** feature would solve this issue perfectly. 

Plus the whole issue is completely **unrealistic**, because even when the CDC connector is able to reconnect on its own (now always the case with Postgres), that process is a slow one and by the time it happens, there will be no more old data in flight through Jet, so new data won't have old data to get reordered with. I can't say it's impossible, but highly unlikely. 

I think we should just close this issue.
