### ISSUE TITLE
`YamlJetConfigResolutionTest` has false failures

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#2395]
Its function depends on a specific order the tests are run. For example, `testResolveFromWorkDirYamlButNotYml()` creates `hazelcast-jet.yaml` in the workdir. If `testResolveFromClasspathYamlAndYml()` runs after it, it will create `hazelcast-jet.yaml` in the classpath dir, but the file from the workdir will be resolved and the property will have a different value and the test will fail. Tests can also pick up files from a previous run (probably not on Jenkins, but locally yes).

The tests also leave config files in shared directories. Ideally, the test should use temporary directories. Less ideally, it might be sufficient if each test deletes used files in a `finally` block.

**Comment by olukas** [comment]
It seems it fails only on Windows due to `The process cannot access the file because it is being used by another process`. Files are deleted in test's `@After` method by `DeclarativeConfigFileHelper` from IMDG (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/config/helpers/DeclarativeConfigFileHelper.java#L267). I was not able to figure out what exactly holds the lock for those files (some of the files created by the test are deleted and some of them cannot be deleted). I modified the method to try to delete the file repeatedly for 10 seconds but `file.delete()` (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/test/java/com/hazelcast/config/helpers/DeclarativeConfigFileHelper.java#L271) always returned `false` and file still existed. 

@viliam-durina do you have any experience with issue like this on Windows?
