### ISSUE TITLE
Usage of the "all-to-one" edge is ill-defined

### ISSUE THREAD

**Issue by mtopolnik** [hazelcast/hazelcast-jet#248]
A distributed "all-to-one" edge will deliver all data to a single instance of processor somewhere in the cluster. However, it is impossible to configure the DAG so that only one processor instance is created; there is a minimum of one per cluster member. This means that it is impossible to avoid processors which get no data.

If the processor's logic is aggregation, such that the output is produced only in the `complete` phase, the processor that receives no data will still output its invalid, empty result. This will then confuse the downstream processors.

One hack to avoid this is emitting output only when some data was received; but there is no general rule that says some data must have been received. Sometimes the empty result is the correct one. In that case the hack will result in no output from the vertex at all.

**Comment by viliam-durina** [comment]
All our aggregating processors don't return empty result: if no key was received, there's not output. So there's just one output value globally.

**Comment by viliam-durina** [comment]
Since some time ago it's also possible to use `forceTotalParallelismOne` with a partitioning key. It will create no-op processors on unused members and it's also possible to choose the member which will have the real processor. In combination with `allToOne(key).distributed()`, all items can be sent to that processor and ensure other processors don't get any data. So I'd say this issue is resolved.
