### ISSUE TITLE
Enhancement: hazelcast-jet-sql, make mapping constants public

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#2704]
I can do this
```
"CREATE MAPPING neil "
                + " TYPE IMap "
                + " OPTIONS ( "
                + " 'keyFormat' = 'portable',"
```

But it would be helpful if the internal constants were exposed, so I could re-use them, less chance for errors.
So I could do
```
"CREATE MAPPING neil"
                + " TYPE " + IMapSqlConnector.TYPE_NAME
                + " OPTIONS ( "
                + " '" + OPTION_KEY_FORMAT + "' = '" + PORTABLE_FORMAT  + "',"
```

**Comment by viliam-durina** [comment]
I would not do this. The API to SQL is completely String-based, you just use the `IMap` identifier directly. We use the constant in tests because we've changed the identifier several times, but after a release we won't change it ever. Oracle also doesn't provide a constant for their `DUAL` table, for example.
