### ISSUE TITLE
Incorrect example in RecordPart.toObject

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#2860]
https://github.com/hazelcast/hazelcast-jet/blob/master/extensions/cdc-debezium/src/main/java/com/hazelcast/jet/cdc/RecordPart.java#L46-L56

1. The argument name is `daysSinceBirth`, but we use it as epoch days.

2. We say that the column in the DB is `DATE`. Maybe that's the case, but I find it surprising that such a column is sent as epoch-days. When you cast `DATE` to `NUMBER` in Oracle, it uses eopch days, but it's a fractional number and the fractional part is the time of the day. 

3. I'm also surprised that `null` is represented as `0`. Maybe that's done by jackson because the set-method accepts a primitive `long`. Maybe it would be better to use `Long`, JSON supports nulls well.

**Comment by jbartok** [comment]
1. The `daysSinceBirth` name is just stupid, a mistake I will fix, nothing to discuss there.

2. Debezium handles the MySQL `DATE` type as [io.debezium.time.Date](https://github.com/debezium/debezium/blob/master/debezium-core/src/main/java/io/debezium/time/Date.java), ie. as the number of days since epoch. ([source](https://debezium.io/documentation/reference/1.2/connectors/mysql.html#_temporal_values))

3. "_MySQL permits you to store a “zero” value of '0000-00-00' as a “dummy date.” In some cases, this is more convenient than using NULL values, and uses less data and index space._" ([source](https://dev.mysql.com/doc/refman/5.7/en/date-and-time-types.html)). "The MySQL connector represents zero-values as null values when the column definition allows null values, or as the epoch day when the column does not allow null values._" ([source](https://debezium.io/documentation/reference/1.2/connectors/mysql.html#_temporal_values))
