### ISSUE TITLE
Hazelcast Jet Kotlin API

### ISSUE THREAD

**Issue by spozdeev** [hazelcast/hazelcast-jet#484]
I want to use Hazelcast Jet with the Kotlin.

The Jet DistributedStream API is not very convenient for using with Kotlin and requires some boilerplate code:
```
val jet = Jet.newJetInstance()
        
val words = jet.getMap<Long, String>("words")
words.put(1, "hazelcast")
words.put(2, "java")
words.put(3, "kotlin")

val streamList = words.stream()
		.map<String>(DistributedFunction<MutableMap.MutableEntry<Long, String>, String> ({ t -> t.value.toUpperCase()}))
		.collect(DistributedCollectors.toList())
println(streamList)
Jet.shutdownAll()
```

It would be nice if the API was similar to the Kotlin collection API:
```
val kotlinList = words.map { it.value.toUpperCase() }
println(kotlinList)
```
Are there any plans for implementing the Kotlin API?

**Comment by thomasnield** [comment]
You can always create a separate project that uses this one as a dependency, and put a nice Kotlin DSL around it. I pretty much did that for [Kotlin-Statistics](https://github.com/thomasnield/kotlin-statistics) which wraps around [Apache Commons Math](http://commons.apache.org/proper/commons-math/index.html).

**Comment by cangencer** [comment]
This seems like a bug in Kotlin to me. There are two overloads of the `map()` function, one is inherited from `java.util.stream.Stream` which takes a `Function` and the other is defined on `DistributedStream` which takes a `DistributedFunction`. `DistributedFunction` extends `Functions` in order to make it `Serializable`. Java by default picks the most specialized overload (`DistributedFunction`), however Kotlin doesn't seem to be able to resolve it the same way. I have also seen some bugs which are similar, but not quite the same: 

https://youtrack.jetbrains.com/issue/KT-11440
https://youtrack.jetbrains.com/issue/KT-18451

**Comment by spozdeev** [comment]
I have implemented a few wrapper methods with names different from the original ones.
It looks like a workaround, but I think it's acceptable for a test project:
```
fun <IN, OUT> DistributedStream<IN>.map_(transform: (IN) -> OUT): DistributedStream<OUT> {
    return this.map(DistributedFunction<IN, OUT>(transform))
}

fun <T> DistributedStream<T>.filter_(predicate: (T) -> Boolean): DistributedStream<T> {
    return this.filter(DistributedPredicate { predicate(it) })
}
```
```
val upper = words.stream()
                .map_ { it.value }
                .map_ { it.toUpperCase() }
                .filter_ { it.isNotEmpty() }
```

**Comment by erokhins** [comment]
@cangencer Yes, this is problem in kotlin compiler: https://youtrack.jetbrains.com/issue/KT-17765
