### ISSUE TITLE
CacheProvider client/server

### ISSUE THREAD

**Issue by kbecic** [hazelcast/hazelcast-jet#493]
Only way to chose `javax.cache.spi.CachingProvider` implementation is by setting 
`-Dhazelcast.jcache.provider.type=[client|server]`. Since both `com.hazelcast.client.cache.impl.HazelcastClientCachingProvider` and `com.hazelcast.cache.impl.HazelcastServerCachingProvider` are on the classpath without above parameter `com.hazelcast.client.cache.impl.HazelcastClientCachingProvider` will always be used.
When using _server_ `com.hazelcast.jet.JetInstance` this will cause  
```
Caused by: javax.cache.CacheException: Error opening URI [hazelcast]
	at com.hazelcast.cache.impl.AbstractHazelcastCachingProvider.getCacheManager(AbstractHazelcastCachingProvider.java:99) ~[hazelcast-jet-0.4.jar:0.4]

Caused by: java.lang.ClassCastException: com.hazelcast.instance.HazelcastInstanceImpl cannot be cast to com.hazelcast.client.impl.HazelcastClientInstanceImpl
	at com.hazelcast.client.cache.impl.HazelcastClientCacheManager.<init>(HazelcastClientCacheManager.java:67) ~[hazelcast-jet-0.4.jar:0.4]
```

It should be possible to exclude/or separate _client_ dependencies when using _server_ `com.hazelcast.jet.JetInstance`

**Comment by gurbuzali** [comment]
Hi,

I couldn't reproduced the behaviour you've mentioned above. Can you please provide a small reproducer so that I can look into it?

**Comment by kbecic** [comment]
This is while using Spring Boot. I will try to write repoducer in following days.

**Comment by kbecic** [comment]
https://github.com/kbecic/hazelcast-jet-example

**Comment by gurbuzali** [comment]
Hi,

I've checked your example. The problem with springboot is, it will try to create a `HazelcastInstance` (server) if hazelcast is in class-path and a `HazelcastInstance`(client) if hazelcast-client in class-path. Since Jet is dependent to both hazelcast and hazelcast-client, spring-boot will create a hazelcast client.

I've tried your example, it creates a `3.7.8` versioned hazelcast client. I've started a server too in another jvm so that client can connect. There was no exception.

Adding `System.setProperty("hazelcast.jcache.provider.type", "server");` to the main method triggers a server creation instead of client.

**Comment by kbecic** [comment]
This should be solved by dedicated hazelcast-jet starter instead of hazelcast starter in Spring Boot. According to their github it is still undecided whether they will create this starter in near future. It won't be part of 2.0 release. I think this issue can be closed at this point.
