### ISSUE TITLE
Setting ttl on 'default' map affects JobRepository.JOB_RECORDS_MAP_NAME

### ISSUE THREAD

**Issue by lukasherman** [hazelcast/hazelcast-jet#592]
Hello Jet Team,
I have observed during debugging mysterious disappearing jobs issue that the ttl set on map entries referenced by JobRepository.JOB_RECORDS_MAP_NAME is the same as set on 'default' map via MapConfig. 
Can you please ensure that 'default' map settings do not interfere with JobRepository entries?

Regards
LH

**Comment by cangencer** [comment]
When adding configuration for internal Jet maps we use `Config.getMapConfig()` which seems to inherit the map default config. We need to use another approach for configuration here, as we don't want the internal map configuration to be overriden.

Are you able to use `*` instead of `default` for your default configuration? This should not override the internal Jet map configuration.

**Comment by lukasherman** [comment]
Thanks can, I will test it with `*` instead.
