### ISSUE TITLE
More built-in output checkers for TestSupport

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast-jet#821]
The TestSupport class provides _SAME_ITEMS_ANY_ORDER_ as an output checker

It would be useful to have a library of these, save the user having to written the common cases

Eg. for list output, to verify the last item
```
public static final BiPredicate<List<?>, List<?>> LAST_ITEM_MATCHES =
	(expected, actual) -> {
		if (actual == null || expected == null || actual.size() == 0 || expected.size() == 0) {
			return false;
		}
		return actual.get(actual.size() - 1).equals(expected.get(expected.size() - 1));
	};
```

**Comment by viliam-durina** [comment]
This particular use case is very specific IMO. It can be done much more simply: you don't need to check for `null`, you can assume that `actual` contains 1 item (because you pass it). You also don't need to assert non-emptiness of `expected`: it will fail anyway with descriptive enough exception, if it's empty:
```
TestSupport
   ...
   .outputChecker((exp, act) -> act.get(exp.size() - 1).equals(exp.get(0)))
   .expectOutput(singletonList(myExpectedLastItem));
```
