### ISSUE TITLE
Handle TimeoutException in kafka sink

### ISSUE THREAD

**Issue by viliam-durina** [hazelcast/hazelcast-jet#947]
The `KafkaProducer.send` is an async operation, but can block if the internal buffer is full. We need to ignore this error.

**Comment by cangencer** [comment]
After some investigation, it looks like it is not very straightforward to handle this exception: The exception is passed to the callback instead of being thrown in `Producer.send()`. This makes it quite awkward to handle, because it means we would need to handle retrying inside the Processor. Furthermore the callback can be called by another thread (it's typically called by the Kafka producer thread) so this causes issues with ordering of messages.

The main issue is that the producer API is "async" but passes exceptions to the callback even though they happen before the method actually returns. So there's no way to distinguish if the message was sent and some exception happened on the broker, or it was never sent in the first place.

It seems the better way to handle this exception is to change `max.block.ms` setting to something higher - by default it's set to 1 minute, and Jet is able to apply backpressure during this period.

We might consider just using the sync API in the future and remove usage of the async API, but needs further investigation.

**Comment by viliam-durina** [comment]
I'm for closing this issue without fixing it. There would need to be a timeout anyway in Jet's retry logic, we won't retry forever. So why not just increase `max.block.ms` in the first place? And if kafka's timeout passes, the job can fail and be restarted. What better can we do?

**Comment by cangencer** [comment]
agreed, let's close this
